In [1]:
# Importación de librerías generales
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing

from sklearn.ensemble import RandomForestClassifier

# Lectura del dataset
iris = pd.read_csv('iris.csv')

In [2]:
# Se aislan las variables de entrada 'X' de la variable predictiva 'y'
X = iris.drop('variety', axis=1)     # Variables 'X', todas menos la etiqueta 'variedad'
y = iris['variety']                  # Variable 'y', la etiqueta 'variedad'

# Se convierten las variables a numpy para posteriormente poder aplicar reshape y adaptar su dimensión
X = np.nan_to_num(X)
y = np.nan_to_num(y)

# Para entrenar los modelos de clasificación es preciso codificar las strings de etiquetas a números
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)

# Finalmente, para evitar overfitting se dividen el conjunto de datos en conjunto de entrenamiento y de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
X_test = X_test.reshape(-X_test.shape[0],X_test.shape[1])    #Reshape de X_test para poder introducirlo

In [5]:
clf = RandomForestClassifier(max_depth=20, n_estimators = 900, criterion = 'gini', random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [6]:
print(metrics.confusion_matrix(y_test, y_pred))

[[21  0  0]
 [ 0 29  1]
 [ 0  3 21]]


In [7]:
print(metrics.accuracy_score(y_test, y_pred))

0.9466666666666667


In [89]:
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 17 20:10:05 2021

@author: Alejandro
"""

print("................................................")
print("Por favor, espere mientras se carga el modelo...")

# Importación de librerías generales
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn import preprocessing

from sklearn import svm

# CARGADO Y PROGRAMA
# ----------------------------------------------------------
# Lectura del dataset
iris = pd.read_csv('iris.csv')

# Se aislan las variables de entrada 'X' de la variable predictiva 'y'
X = iris.drop('variety', axis=1)     # Variables 'X', todas menos la etiqueta 'variedad'
y = iris['variety']                  # Variable 'y', la etiqueta 'variedad'

# Se convierten las variables a numpy para posteriormente poder aplicar reshape y adaptar su dimensión
X = np.nan_to_num(X)
y = np.nan_to_num(y)

# Para entrenar los modelos de clasificación es preciso codificar las strings de etiquetas a números
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)

# Finalmente, para evitar overfitting se dividen el conjunto de datos en conjunto de entrenamiento y de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
X_test = X_test.reshape(-X_test.shape[0],X_test.shape[1])    #Reshape de X_test para poder introducirlo

# Se entrena el modelo
clf = svm.SVC(kernel="poly", gamma='auto', C=20)
clf.fit(X_train, y_train)

# INTERFAZ
# ----------------------------------------------------------

loop = 1

print("¡El modelo está listo!")
print("................................................")
print("")

print("LAS MEDIDAS SON EN (cm)")


while loop == 1:
    
    sl = input("Introduce LONGITUD de SÉPALO (4.3 a 7.9)\n")
    sw = input("Introduce ANCHO de SÉPALO (2.0 a 4.4)\n")
    pl = input("Introduce LONGITUD de PÉTALO (1.0 a 6.9)\n")
    pw = input("Introduce ANCHO de PÉTALO (0.1 a 2.5)\n")
    print("")
    
    prediction = clf.predict([[sl,sw,pl,pw]])
    
    if prediction == [0]:
        print("¡Es una flor de variedad SETOSA!")
    elif prediction == [1]:
        print("¡Es una flor de variedad VERSICOLOR!")
    elif prediction == [2]:
        print("¡Es una flor de variedad VIRGINICA!")
    
    print("")
    print("¿Seguir prediciendo (Si 1 / No 0)?")
    loop = int(input())


................................................
Por favor, espere mientras se carga el modelo...
¡El modelo está listo!
................................................

LAS MEDIDAS SON EN (cm)
Introduce LONGITUD de SÉPALO (4.3 a 7.9)
4
Introduce ANCHO de SÉPALO (2.0 a 4.4)
6
Introduce LONGITUD de PÉTALO (1.0 a 6.9)
8
Introduce ANCHO de PÉTALO (0.1 a 2.5)
3

¡Es una flor de variedad VIRGINICA!

¿Seguir prediciendo (Si 1 / No 0)?
0


In [88]:
from tkinter import *
from tkinter.ttk import *

val1 = 0

window = Tk()
window.title("Introducir Campos")
# window.geometry('250x200') #Se omite para que la ventana se ajuste al tamaño

data1 = 4.3
data2 = 2.0
data3 = 1.0
data4 = 0.1



def l1 (val):
    global data1
    data1 = round(ent1.get(),2)
    lbl1b.configure(text = data1)
def l2 (val):
    global data2
    data2 = round(ent2.get(),2)
    lbl2b.configure(text = data2)
def l3 (val):
    global data3
    data3 = round(ent3.get(),2)
    lbl3b.configure(text = data3)
def l4 (val):
    global data4
    data4 = round(ent4.get(),2)
    lbl4b.configure(text = data4)
    
def predecir ():    
    prediction = clf.predict([[data1,data2,data3,data4]]) 
    
    if prediction == [0]:
        text = "¡Es una flor de variedad SETOSA!"
    elif prediction == [1]:
        text = "¡Es una flor de variedad VERSICOLOR!"
    elif prediction == [2]:
        text = "¡Es una flor de variedad VIRGINICA!"
        
    lbl5.configure(text = text)
    
lbl1 = Label(window, text="LONGITUD de SÉPALO (4.3 a 7.9)")
lbl1.grid(sticky="w", row=0, column=0) 
ent1 = Scale(window, from_=4.3, to=7.9, variable=data1, command=l1)
ent1.grid(sticky="w", row=0, column=1) 
lbl1b = Label(window, text=data1, width=10)
lbl1b.grid(sticky="w", row=0, column=2) 

lbl2 = Label(window, text="ANCHO de SÉPALO (2.0 a 4.4)")
lbl2.grid(sticky="w", row=1, column=0) 
ent2 = Scale(window, from_=2.0 , to=4.4, variable=data2, command=l2)
ent2.grid(sticky="w", row=1, column=1) 
lbl2b = Label(window, text=data2)
lbl2b.grid(sticky="w", row=1, column=2) 

lbl3 = Label(window, text="LONGITUD de PÉTALO (1.0 a 6.9)")
lbl3.grid(sticky="w", row=2, column=0) 
ent3 = Scale(window, from_=1.0, to=6.9, variable=data3, command=l3)
ent3.grid(sticky="w", row=2, column=1) 
lbl3b = Label(window, text=data3)
lbl3b.grid(sticky="w", row=2, column=2) 

lbl4 = Label(window, text="ANCHO de PÉTALO (0.1 a 2.5)")
lbl4.grid(sticky="w", row=3, column=0) 
ent4 = Scale(window, from_=0.1, to=2.5, variable=data4, command=l4)
ent4.grid(sticky="w", row=3, column=1) 
lbl4b = Label(window, text=data4)
lbl4b.grid(sticky="w", row=3, column=2) 

btn = Button(window, text="Predecir Variedad", command=predecir)
btn.grid(sticky="ew", row=4, column=0, columnspan=3)

lbl5 = Label(window, text="PREDICCIÓN", anchor="center")
lbl5.grid(sticky="ew", row=5, column=0, columnspan=3)


window.mainloop()